# Ranker Settings
model_name: 'baseline_lgb+cat_t21'
save_file_dir: 'model/ranker/'
preprocessed_train_path: 'data/processed/train.pickle'

model_path_list:
  - 'model/ranker/baseline_lgb_t21'
  - 'model/ranker/baseline_cat_t21'

model_weight_list:
  - 0.4
  - 0.6

method: 'rank' # ['score', 'rank']

cv_params:
  date_th: '2017-04-23'
  train_period: 21
  eval_period: 7