# Ranker Settings
model_name: 'exp030'
save_file_dir: 'model/ranker/'
preprocessed_train_path: 'data/processed/train.pickle'

model_path_list:
  - 'model/ranker/exp027'
  - 'model/ranker/exp028'
  - 'model/ranker/exp029'

model_weight_list:
  - 1.0
  - 1.0
  - 1.0

method: 'score' # ['score', 'rank']

cv_params:
  date_th: '2017-04-23'
  train_period: 14
  eval_period: 7