# Ranker Settings
model_name: 'exp029'
save_file_dir: 'model/ranker/'
preprocessed_train_path: 'data/processed/train.pickle'
train_features_path: 'data/features/features_2017-04-16_t14_baseline.pickle'
valid_features_path: 'data/features/features_2017-04-23_t14_baseline.pickle'
test_features_path: 'data/features/features_2017-04-30_t14_baseline.pickle'

negative_sampling: True
negative_sampling_rate: 0.5
negative_sampling_random_state: 2

target_col: 'target'
drop_cols:
  - 'user_id'
  - 'product_id'
  - 'target'

category_cols:
  - 'item_category'

model_params:
  objective: 'lambdarank'
  lambdarank_truncation_level: 22
  label_gain: '0,1,3,7'
  lambdarank_norm: True
  metric: 'ndcg'
  learning_rate: 0.02
  eval_at: '22'
  num_leaves: 256
  max_bin: 128

train_params:
  num_boost_round: 1000
  early_stopping_rounds: 20
  verbose_eval: 20

cv_params:
  date_th: '2017-04-23'
  train_period: 14
  eval_period: 7