# Retriever Settings
test_data_path: 'data/raw/test.tsv'
preprocessed_data_dir: 'data/processed'    # (str) Directory of preprocessed data.
pairs_dir: 'data/pairs'                    # (str) Directory of user-item pairs (candidates for ranking).
pairs_file_suffix: 'baseline'
co_occur_items_dir: 'model/co_occur_items' # (str) Directory of cooccurence item data. (used in CoOccurrenceItem Class)

date_th:                                   # (str) List of boundary between train period and evaluation period.
  - '2017-04-16'
  - '2017-04-23'
  - '2017-04-30'
train_period: 14                           # (int) Number of days of train period.
eval_period: 7                             # (int) Number of days of evaluation period.


popular_item:
  top_n: 50

favorite_item:
  top_n: 200

co_occurence_item:
  top_n: 200

recbole_bpr:
  model_name: 'BPR'
  config_file_list:
    - 'config/recbole_base.yaml'
    - 'config/recbole_bpr.yaml'
  checkpoint_path:
    '2017-04-16': 'model/bpr/bpr_2017-04-16.pth'
    '2017-04-23': 'model/bpr/bpr_2017-04-23.pth'
    '2017-04-30': 'model/bpr/bpr_2017-04-30.pth'
  batch_size: 64
  top_n: 50

recbole_itemknn:
  model_name: 'ItemKNN'
  config_file_list:
    - 'config/recbole_base.yaml'
    - 'config/recbole_itemknn.yaml'
  checkpoint_path:
    '2017-04-16': 'model/itemknn/itemknn_2017-04-16.pth'
    '2017-04-23': 'model/itemknn/itemknn_2017-04-23.pth'
    '2017-04-30': 'model/itemknn/itemknn_2017-04-30.pth'
  batch_size: 64
  top_n: 50

recbole_recvae:
  model_name: 'RecVAE'
  config_file_list:
    - 'config/recbole_base.yaml'
    - 'config/recbole_recvae.yaml'
  checkpoint_path:
    '2017-04-16': 'model/recvae/recvae_2017-04-16.pth'
    '2017-04-23': 'model/recvae/recvae_2017-04-23.pth'
    '2017-04-30': 'model/recvae/recvae_2017-04-30.pth'
  batch_size: 64
  top_n: 50

recbole_item2vec:
  model_name: 'Item2Vec'
  config_file_list:
    - 'config/recbole_base.yaml'
    - 'config/recbole_item2vec.yaml'
  checkpoint_path:
    '2017-04-16': 'model/item2vec/item2vec_2017-04-16.pth'
    '2017-04-23': 'model/item2vec/item2vec_2017-04-23.pth'
    '2017-04-30': 'model/item2vec/item2vec_2017-04-30.pth'
  batch_size: 64
  top_n: 50

concat_retriever:
  top_n: 300